# name: Workflow GitHub Action
# Run Workflow when push on main
on:
  push:
    branches:
      - master
jobs:
  execute:
    name: Update
    runs-on: ubuntu-latest
    steps:
    - name: Connecting on remote VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
                  sudo -u ${{ secrets.SSH_USER }} -H bash -l -c 'cd /home/${{ secrets.SSH_USER }}/GIT/pinyin && git pull'